import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="layout">
          <nav className="sidebar">
            <ul>
              <li><i className="icon-home"></i> Home</li>
              <li><i className="icon-about"></i> About</li>
              <li><i className="icon-services"></i> Services</li>
              <li><i className="icon-contact"></i> Contact</li>
            </ul>
          </nav>
          <main className="content">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}