import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaHome, FaUser, FaCog } from "react-icons/fa";
import { AuthProvider } from "./lib/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="layout">
          <aside className="sidebar">
            <nav>
              <ul>
                <li><FaHome /> Home</li>
                <li><FaUser /> Profile</li>
                <li><FaCog /> Settings</li>
              </ul>
            </nav>
          </aside>
          <main className="main-content">
            <header className="top-bar">
              <button>Login</button>
              <button>Sign Up</button>
            </header>
              <AuthProvider>{children}</AuthProvider>
            <footer className="footer">
              <p>&copy; 2023 Your Company</p>
            </footer>
          </main>
        </div>
      </body>
    </html>
  );
}